// <auto-generated />
namespace zapread.com.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_User_AboutMe : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_User_AboutMe));
        
        string IMigrationMetadata.Id
        {
            get { return "201805170122451_Add_User_AboutMe"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
