// <auto-generated />
namespace zapread.com.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UsersHaveGroups : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UsersHaveGroups));
        
        string IMigrationMetadata.Id
        {
            get { return "201805212157010_UsersHaveGroups"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
