// <auto-generated />
namespace zapread.com.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class global_earning_spending : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(global_earning_spending));
        
        string IMigrationMetadata.Id
        {
            get { return "202201270152510_global_earning_spending"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
